uploads = []
generated = []

[[outputs]]
id = "Wp4DU6vX036SAAfQAseyk"
uri = "file://screenshots/email-connect.jpg"
type = "image"
title = "Gmail connect page preview"
logical_id = "4890c635-11d1-4831-9d61-097de6bcf080"
