import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { Loader2, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { PageTransition } from '@/components/ui/page-transition';
import { useToast } from '@/hooks/use-toast';
import { creditApi, creditErrorMessage, formatUsdMicros, newCreditIdempotencyKey, parseUsdMicros, type CreditPolicy, type CreditUsageResponse } from '@/lib/credit-api';

export function AdminCreditsPage() {
  const { toast } = useToast(); const [policy, setPolicy] = useState<CreditPolicy | null>(null); const [usage, setUsage] = useState<CreditUsageResponse | null>(null);
  const [userId, setUserId] = useState(''); const [amount, setAmount] = useState(''); const [reason, setReason] = useState(''); const [changeReason, setChangeReason] = useState('');
  const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setPolicy(await creditApi.adminPolicy()); } catch (e) { toast({ title: creditErrorMessage(e, 'USD tariff policy is unavailable'), variant: 'destructive' }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const lookup = async () => { if (!userId.trim()) return; try { setUsage(await creditApi.adminUsage(userId.trim())); } catch (e) { toast({ title: creditErrorMessage(e, 'Account usage is unavailable'), variant: 'destructive' }); } };
  const adjust = async () => { const micros = parseUsdMicros(amount); if (!userId.trim() || !micros || !reason.trim()) return; setSaving(true); try { await creditApi.adminAdjustment({ userId: userId.trim(), amountUsdMicros: micros, reason: reason.trim(), idempotencyKey: newCreditIdempotencyKey() }); toast({ title: 'USD adjustment posted', description: `${formatUsdMicros(micros)} posted to ${userId.trim()}.` }); setAmount(''); setReason(''); await lookup(); } catch (e) { toast({ title: creditErrorMessage(e, 'Adjustment could not be posted'), variant: 'destructive' }); } finally { setSaving(false); } };
  const update = (patch: Partial<CreditPolicy>) => setPolicy((current) => current ? { ...current, ...patch } : current);
  const updateRate = (key: string, value: string) => setPolicy((current) => current ? { ...current, rateCards: { ...current.rateCards, [key]: { ...current.rateCards[key], usdMicrosPerHour: value.trim() === '' ? null : parseUsdMicros(value) } } } : current);
  const savePolicy = async () => { if (!policy || !changeReason.trim()) return; setSaving(true); try { const next = await creditApi.updateAdminPolicy({ rateCards: policy.rateCards, monthlyGrantUsdMicros: policy.monthlyGrantUsdMicros, rolloverCapUsdMicros: policy.rolloverCapUsdMicros, rolloverExpiryDays: policy.rolloverExpiryDays, overrunMarginPercent: policy.overrunMarginPercent }, policy.version, changeReason.trim()); setPolicy(next); setChangeReason(''); toast({ title: `Tariff policy v${next.version} published` }); } catch (e) { toast({ title: creditErrorMessage(e, 'Policy could not be published'), variant: 'destructive' }); } finally { setSaving(false); } };
  if (loading || !policy) return <PageTransition className="mx-auto max-w-5xl space-y-6"><div className="h-12 w-64 animate-pulse rounded-lg bg-muted" /><div className="h-64 animate-pulse rounded-2xl bg-muted" /><Card role="alert"><CardHeader><CardTitle>USD tariff policy is unavailable</CardTitle><CardDescription>Only authorized administrators can manage this policy.</CardDescription></CardHeader><CardContent><Button onClick={() => void load()}><RefreshCw className="me-2 h-4 w-4" /> Try again</Button></CardContent></Card></PageTransition>;
  return <PageTransition className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-primary"><ShieldCheck className="h-3.5 w-3.5" /> Admin control room</p><h1 className="text-3xl font-display font-bold tracking-tight md:text-4xl">USD tariff policy</h1><p className="mt-2 max-w-2xl text-muted-foreground">Publish auditable provider rates and post adjustments or refunds in USD microunits.</p></div><Link href="/credits" className="inline-flex min-h-10 items-center rounded-md border border-border px-4 text-sm font-medium"><WalletCards className="me-2 h-4 w-4" /> Personal wallet</Link></header>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Active policy <Badge className="ms-2">v{policy.version}</Badge></CardTitle><CardDescription>All rates are fixed-point USD values. OpenAI rates remain unconfigured until entered.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label>Monthly grant (USD)</Label><Input value={formatUsdMicros(policy.monthlyGrantUsdMicros)} onChange={(e) => update({ monthlyGrantUsdMicros: parseUsdMicros(e.target.value) })} /></div><div><Label>Rollover cap (USD)</Label><Input value={formatUsdMicros(policy.rolloverCapUsdMicros)} onChange={(e) => update({ rolloverCapUsdMicros: parseUsdMicros(e.target.value) })} /></div><div><Label>Rollover expiry days</Label><Input type="number" value={policy.rolloverExpiryDays} onChange={(e) => update({ rolloverExpiryDays: Math.max(1, Math.trunc(Number(e.target.value) || 1)) })} /></div><div><Label>Overrun margin percent</Label><Input type="number" value={policy.overrunMarginPercent} onChange={(e) => update({ overrunMarginPercent: Math.max(0, Math.trunc(Number(e.target.value) || 0)) })} /></div></div><div className="space-y-2">{Object.entries(policy.rateCards).map(([key, card]) => <div key={key} className="rounded-lg border border-border/70 p-3"><p className="font-medium">{card.provider} · {card.mode} · {card.model}</p><p className="mb-2 text-sm text-muted-foreground">{card.meter}</p><Input aria-label={`${key} USD per hour`} value={card.usdMicrosPerHour == null ? '' : formatUsdMicros(card.usdMicrosPerHour)} onChange={(e) => updateRate(key, e.target.value)} placeholder="Not configured" /></div>)}</div><div><Label htmlFor="policy-reason">Reason for next version</Label><Input id="policy-reason" value={changeReason} onChange={(e) => setChangeReason(e.target.value)} placeholder="Explain the tariff change" /></div><Button onClick={() => void savePolicy()} disabled={saving || !changeReason.trim()}>{saving && <Loader2 className="me-2 h-4 w-4 animate-spin" />}Publish policy v{policy.version + 1}</Button></CardContent></Card>
    <Card className="h-fit"><CardHeader><CardTitle>Post USD adjustment</CardTitle><CardDescription>Use a signed decimal amount such as $5.00 or -$0.25. The API receives integer microunits.</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="admin-user">User ID</Label><Input id="admin-user" value={userId} onChange={(e) => setUserId(e.target.value)} placeholder="usr_…" /></div><div><Label htmlFor="admin-amount">Amount (USD)</Label><Input id="admin-amount" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="$5.00 or -$0.25" /></div><div><Label htmlFor="admin-reason">Reason</Label><Input id="admin-reason" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Customer support adjustment" /></div><Button className="w-full" onClick={() => void adjust()} disabled={saving || !userId.trim() || !reason.trim() || !parseUsdMicros(amount)}>{saving && <Loader2 className="me-2 h-4 w-4 animate-spin" />}Post adjustment</Button><Button variant="outline" className="w-full" onClick={() => void lookup()} disabled={!userId.trim()}>Inspect account</Button></CardContent></Card></div>
    {usage && <Card><CardHeader><CardTitle>Account ledger: {userId}</CardTitle><CardDescription>Current account counters and immutable entries.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-6">{Object.entries(usage.usage).filter(([key]) => key.endsWith('Micros')).map(([key, value]) => <div key={key}><p className="text-xs text-muted-foreground">{key.replace('UsdMicros', '')}</p><p className="font-mono text-lg">{formatUsdMicros(value as number)}</p></div>)}</div><div className="space-y-2">{usage.events.map((event) => <div key={event.id} className="rounded-lg border border-border/60 p-3 text-sm"><p className="font-medium">{event.eventType} · {formatUsdMicros(event.amountUsdMicros)}</p><p className="text-xs text-muted-foreground">{event.createdAt} · reservation {event.reservationId}</p></div>)}</div></CardContent></Card>}</PageTransition>;
}